Include chaos functional workload stages into gitlab ci (GCP)
Signed-off-by: Sudarshan <sudarshan.darga@cloudbyte.com>

diff --git a/script/apps/mongo/chaos/jiva/volume-controller-failure b/script/apps/mongo/chaos/jiva/volume-controller-failure
--- a/script/apps/mongo/chaos/jiva/volume-controller-failure
+++ b/script/apps/mongo/chaos/jiva/volume-controller-failure
@@ -1,36 +1,35 @@
 #!/bin/bash
-set -ex
+set -x
 
-######################
-##   ENVIRONMENT    ##
-######################
+#################
+## ENVIRONMENT ##
+#################
 
 ## TODO: Ideally, run_metadata should be passed as gitlab runner (CI runtime) ENV
 run_metadata=""
 
-## https://github.com/openebs/litmus/blob/master/apps/percona/deployers/test_vars.yml
-test_name="openebsinstaller"
+## https://github.com/openebs/litmus/blob/master/apps/percona/chaos/openebs_target_failure/test_vars.yml
+test_name="openebs-target-failure" 
 
 if [[ -n "$run_metadata" ]]; then
   test_name="$test_name-$run_metadata"
-fi
-
-## Display pipeline info
-echo $CI_PIPELINE_ID; echo $CI_PIPELINE_IID; echo $CI_COMMIT_SHA
-
+fi 
+      
 ################
 ## FUNCTIONS  ##
 ################
+
 error_handler()
 {
 rc=$1; message=$(echo $2 | cut -d "=" -f 2); act=$(echo $3 | cut -d "=" -f 2)
 if [ $rc -ne 0 ]; then
   echo "$message"
   if [ "$act" == "exit" ]; then
-    exit 1
+    exit 1 
   fi
 fi
 }
+
 task_delimiter()
 {
 printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' "%"
@@ -41,31 +40,22 @@ printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' "%"
 ###################
 
 ## Derive the kubeconfig of the AWS cluster into the gitlab job runner pod
-## "aws-openebs" is a shared path for the gitlab runner passed as artifact by gitlab 
+## "gcp-openebs" is a shared path for the gitlab runner passed as artifact by gitlab 
 
 echo "Setting up test dependencies.."
 
-# TODO - Investigate need another folder called aws-openebs
-mkdir .kube-openebs
 mkdir ~/.kube
-cp  .kube/config .kube-openebs/config
-cp  .kube/config ~/.kube/config
-cat /openebs/e2e-gcp/.kube/clusters > .kube-openebs/clusters
-
-for i in efk-vars.yml efk.yml get_url.yml; do
-  wget https://raw.githubusercontent.com/openebs/e2e-infrastructure/master/production/efk-client/playbook/$i
-done
-
-echo "EFK: Deploying Aggregrator and Forwarder on client"
-ansible-playbook efk.yml --extra-vars "commit_id=$CI_COMMIT_SHA pipeline_id=$CI_PIPELINE_ID" 
+cp .kube-openebs/config ~/.kube/config
+mkdir ~/logs
+cp .kube-openebs/clusters ~/logs
 
 ## Clone the litmus repo, checkout the e2e branch, navigate to litmus root 
 
 #git clone https://github.com/atulabhi/litmus.git
 #cd litmus; git checkout v0.7-RC1
 
-git clone https://github.com/dargasudarshan/litmus.git
-cd litmus, git checkout openebssetup
+git clone https://github.com/openebs/litmus.git
+cd litmus
 
 task_delimiter;
 
@@ -73,18 +63,38 @@ task_delimiter;
 ## LITMUS PRECONDITIONING ##
 ############################
 
-## TODO: Add logic to replace job ENV based on run instance intent 
+## TODO: Add logic to replace job ENV (SC, PVC, LABEL, NS) based on run instance intent 
 ## TODO: Add logic to add ENV for run_instance_metadata/RunID
+## TODO: Change location of chaos jobs
+
+: << EOF
+  ----------------------------------------------------------------------------------
+ | specAttribute        | kind     | percona             | mongodb                  |
+  ----------------------------------------------------------------------------------|
+ | appLabel             | env      | name=percona        | app=mongo                |
+ | pvcName              | env      | percona-mysql-claim | openebs-mongo-mongo-0    | 
+ | appNamespace         | env      | app-percona-ns      | app-mongo-ns		    | 
+  ----------------------------------------------------------------------------------
+EOF
+
+cp apps/percona/chaos/openebs_target_failure/run_litmus_test.yml run_mongo_jiva_controller_failure.yml
+
+sed -i -e 's/''name=percona''/''app=mongo''/g' \
+-e 's/value: app-percona-ns/value: app-mongo-ns/g' \
+-e 's/value: percona-mysql-claim/value: openebs-mongo-mongo-0/g' run_mongo_jiva_controller_failure.yml
+
 
 #################
 ## RUNNER MAIN ##
 #################
 
-echo "Running litmus test for openebs deploy.."
+echo "Running the litmus test.."
 
-jobNameCmd="kubectl get jobs -n litmus --no-headers -o jsonpath='{.items[?(@.metadata.labels.provider==\"openebs-setup\")].metadata.name}'"
+## Create the litmus job for percona app chaos test: openebs-target-failure
 
-job_deploy_out=$(kubectl create -f providers/openebs/installers/operator/master/litmusbook/openebs_setup.yaml) && \
+jobNameCmd="kubectl get jobs -n litmus --no-headers -o jsonpath='{.items[?(@.metadata.labels.name==\"openebs-target-failure\")].metadata.name}'"
+
+job_deploy_out=$(kubectl create -f run_mongo_jiva_controller_failure.yml) && \
 job_name=$(eval $jobNameCmd); retcode=$?
 error_handler $retcode msg="Unable to run litmusbook, exiting" action="exit"
 
@@ -104,8 +114,8 @@ jobStateCmd="kubectl get pod ${litmus_pod} --no-headers -n litmus -o custom-colu
 ## TODO: Consider cases where litmus pod is evicted
 
 while [[ ! $(eval $containerStateCmd) =~ 'terminated' ]]; do
-  sleep 1
-done
+  sleep 1 
+done 
 
 while [[ $(eval $jobStateCmd) =~ 'Running' ]]; do
    sleep 1
@@ -117,16 +127,15 @@ task_delimiter;
 ## Printing the test logs & cluster state for debug purposes 
 
 echo "Dumping Litmus test pod logs for debug"; echo ""
-kubectl logs $litmus_pod -n litmus -c ansibletest
-task_delimiter;
+kubectl logs $litmus_pod -n litmus -c ansibletest 
+task_delimiter; 
 
 echo "Dumping state of cluster post job run"; echo ""
 kubectl get pods --all-namespaces
 kubectl get pvc --all-namespaces
-kubectl get sc 
+kubectl get sc
 
-task_delimiter;
-
+task_delimiter; 
 
 ## Check the test status & result from the litmus result custom resource
 
@@ -137,11 +146,11 @@ error_handler $retcode msg="Unable to find litmus result custom resource, exitin
 if [[ $testStatus == "completed" ]]; then
   if [[ $testResult == "Pass" ]]; then
     echo "TEST: PASS"
-  else
-    echo "TEST: FAILED"; exit 1
+  else 
+    echo "TEST: FAILED"; exit 1 
   fi
 else
-  echo "Test Execution was aborted"; exit 1
-fi
+  echo "Test Execution was aborted"; exit 1 
+fi 
 
 
diff --git a/script/apps/mongo/workload/cstor/mongo-app-workload-cstor b/script/apps/mongo/workload/cstor/mongo-app-workload-cstor
--- a/script/apps/mongo/workload/cstor/mongo-app-workload-cstor
+++ b/script/apps/mongo/workload/cstor/mongo-app-workload-cstor
@@ -1,36 +1,35 @@
 #!/bin/bash
-set -ex
+set -x
 
-######################
-##   ENVIRONMENT    ##
-######################
+#################
+## ENVIRONMENT ##
+#################
 
 ## TODO: Ideally, run_metadata should be passed as gitlab runner (CI runtime) ENV
-run_metadata=""
+run_metadata="cstor"
 
-## https://github.com/openebs/litmus/blob/master/apps/percona/deployers/test_vars.yml
-test_name="openebsinstaller"
+https://github.com/openebs/litmus/blob/master/apps/percona/workload/test_vars.yml
+test_name="mongodb-loadgen" 
 
 if [[ -n "$run_metadata" ]]; then
   test_name="$test_name-$run_metadata"
-fi
-
-## Display pipeline info
-echo $CI_PIPELINE_ID; echo $CI_PIPELINE_IID; echo $CI_COMMIT_SHA
-
+fi 
+      
 ################
 ## FUNCTIONS  ##
 ################
+
 error_handler()
 {
 rc=$1; message=$(echo $2 | cut -d "=" -f 2); act=$(echo $3 | cut -d "=" -f 2)
 if [ $rc -ne 0 ]; then
   echo "$message"
   if [ "$act" == "exit" ]; then
-    exit 1
+    exit 1 
   fi
 fi
 }
+
 task_delimiter()
 {
 printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' "%"
@@ -45,27 +44,18 @@ printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' "%"
 
 echo "Setting up test dependencies.."
 
-# TODO - Investigate need another folder called aws-openebs
-mkdir .kube-openebs
 mkdir ~/.kube
-cp  .kube/config .kube-openebs/config
-cp  .kube/config ~/.kube/config
-cat /openebs/e2e-gcp/.kube/clusters > .kube-openebs/clusters
-
-for i in efk-vars.yml efk.yml get_url.yml; do
-  wget https://raw.githubusercontent.com/openebs/e2e-infrastructure/master/production/efk-client/playbook/$i
-done
-
-echo "EFK: Deploying Aggregrator and Forwarder on client"
-ansible-playbook efk.yml --extra-vars "commit_id=$CI_COMMIT_SHA pipeline_id=$CI_PIPELINE_ID" 
+cp .kube-openebs/config ~/.kube/config
+mkdir ~/logs
+cp .kube-openebs/clusters ~/logs
 
 ## Clone the litmus repo, checkout the e2e branch, navigate to litmus root 
 
 #git clone https://github.com/atulabhi/litmus.git
 #cd litmus; git checkout v0.7-RC1
 
-git clone https://github.com/dargasudarshan/litmus.git
-cd litmus, git checkout openebssetup
+git clone https://github.com/openebs/litmus.git
+cd litmus 
 
 task_delimiter;
 
@@ -73,18 +63,42 @@ task_delimiter;
 ## LITMUS PRECONDITIONING ##
 ############################
 
-## TODO: Add logic to replace job ENV based on run instance intent 
+## TODO: Add logic to replace job ENV (SC, PVC, LABEL, NS) based on run instance intent 
 ## TODO: Add logic to add ENV for run_instance_metadata/RunID
+
+
+: << EOF
+  ------------------------------------------------------------------------------------
+ | specAttribute        | kind     | jiva               | cStor-sparse                 |
+  ------------------------------------------------------------------------------------
+ | litmusJobLabel       | jobSpec  | mongodb-loadjob    | mongodb-loadjob-cstor        |
+ | appNamespace         | env      | app-mongo-ns       | mongodb-cstor                |
+ | runID                | env(add) |    -               | cstor 
+  ------------------------------------------------------------------------------------
+EOF
+
+cp apps/mongodb/workload/run_litmus_test.yml run_cstor_litmus_test.yml
+
+sed -i -e 's/loadgen: mongodb-loadjob/loadgen: mongodb-loadjob-cstor/g' \
+-e 's/value: app-mongo-ns/value: mongodb-cstor/g' run_cstor_litmus_test.yml
+
+sed -i '/command:/i \
+          - name: RUN_ID\
+            value: '"$run_metadata"'\
+' run_cstor_litmus_test.yml
+
 
 #################
 ## RUNNER MAIN ##
 #################
 
-echo "Running litmus test for openebs deploy.."
+echo "Running the litmus test.."
 
-jobNameCmd="kubectl get jobs -n litmus --no-headers -o jsonpath='{.items[?(@.metadata.labels.provider==\"openebs-setup\")].metadata.name}'"
+## Create the litmus job for percona app deploy
 
-job_deploy_out=$(kubectl create -f providers/openebs/installers/operator/master/litmusbook/openebs_setup.yaml) && \
+jobNameCmd="kubectl get jobs -n litmus --no-headers -o jsonpath='{.items[?(@.metadata.labels.loadgen==\"mongodb-loadjob-cstor\")].metadata.name}'"
+
+job_deploy_out=$(kubectl create -f run_cstor_litmus_test.yml) && \
 job_name=$(eval $jobNameCmd); retcode=$?
 error_handler $retcode msg="Unable to run litmusbook, exiting" action="exit"
 
@@ -104,8 +118,8 @@ jobStateCmd="kubectl get pod ${litmus_pod} --no-headers -n litmus -o custom-colu
 ## TODO: Consider cases where litmus pod is evicted
 
 while [[ ! $(eval $containerStateCmd) =~ 'terminated' ]]; do
-  sleep 1
-done
+  sleep 1 
+done 
 
 while [[ $(eval $jobStateCmd) =~ 'Running' ]]; do
    sleep 1
@@ -117,16 +131,15 @@ task_delimiter;
 ## Printing the test logs & cluster state for debug purposes 
 
 echo "Dumping Litmus test pod logs for debug"; echo ""
-kubectl logs $litmus_pod -n litmus -c ansibletest
-task_delimiter;
+kubectl logs $litmus_pod -n litmus -c ansibletest 
+task_delimiter; 
 
 echo "Dumping state of cluster post job run"; echo ""
 kubectl get pods --all-namespaces
 kubectl get pvc --all-namespaces
-kubectl get sc 
+kubectl get sc
 
-task_delimiter;
-
+task_delimiter; 
 
 ## Check the test status & result from the litmus result custom resource
 
@@ -137,11 +150,11 @@ error_handler $retcode msg="Unable to find litmus result custom resource, exitin
 if [[ $testStatus == "completed" ]]; then
   if [[ $testResult == "Pass" ]]; then
     echo "TEST: PASS"
-  else
-    echo "TEST: FAILED"; exit 1
+  else 
+    echo "TEST: FAILED"; exit 1 
   fi
 else
-  echo "Test Execution was aborted"; exit 1
-fi
+  echo "Test Execution was aborted"; exit 1 
+fi 
 
 
